### ISSUE TITLE
Rygar gfx problem using tecmo core

### ISSUE THREAD

**Issue by mdd45** [MiSTer-devel/Arcade-Tecmo_MiSTer#2] opened 2020-06-15 14:52 UTC
im getting graphics errors in Rygar like in the video below:
 
[Rygar.zip](https://github.com/MiSTer-devel/Arcade-Tecmo_MiSTer/files/4781043/Rygar.zip)

**Comment by gomadosnitro** [comment] 2020-06-15 16:22
Is working well here, whith last version Arcade-Tecmo_20200615

**Comment by mdd45** [comment] 2020-06-15 17:36
the problem was the mra, it seems to work.

**Comment by mdd45** [comment] 2020-06-16 21:56
Still having the gfx errors not related to mra's it seems to be random....

**Comment by nullobject** [comment] 2020-06-16 23:34
@mdd45 Oh weird, that looks like a SDRAM issue. Thanks for reporting it.

A couple questions:

* Which SDRAM module are you using?
* Is it only Rygar that is having issues? What about Silkworm or Gemini Wing?

**Comment by mdd45** [comment] 2020-06-17 05:53
Hello, i have the 128mb horizontal ram board from Antonio Villena. With 15/6 build i had random gfx problems only with Rygar, but with 16/6 build i have gfx problems with all 3 games of technology core. Memtest gives me no errors. It looks like the now fixed problem with some square games (like ff6) in snes core and 128mb modules.. .

**Comment by Left-Empty** [comment] 2020-06-17 06:05
I have a 128 RAM board as well, and am experiencing totally random glitches each time I boot Rygar...  and like mdd45 I am now experiencing them in Gemini Wing and Silkworm as well with today's update.

Odds are we got the them sort of ram. No error either, and no issues in any other cores (but I confess to not playing the Super Nintendo ;D )

Cheers!

**Comment by mdd45** [comment] 2020-06-17 06:33
So further testing, when I boot mister cold I have no errors with any of the 3 games. After playing for 15minutes with neo geo core for example and then trying to boot Rygar i get random errors. it looks like the sdram issue that snes core had.

**Comment by Left-Empty** [comment] 2020-06-17 09:07
Our paths diverge here: I am experiencing errors no matter what.

**Comment by nullobject** [comment] 2020-06-17 09:16
I have a 128MB module in the mail, so hopefully I will soon be able to reproduce this issue myself.

Sorry for the hassle.

**Comment by sorgelig** [comment] 2020-06-17 17:23
@nullobject keep in mind, non-official SDRAM module has completely different routing and it's possible to have different timings. You need to test on official 128MB module.

**Comment by nullobject** [comment] 2020-06-17 23:19
@sorgelig Good point, will do. It should be arriving in the mail any day now :smile:

**Comment by Left-Empty** [comment] 2020-06-30 22:20
I just noticed yesterday (didn't get a notification or simply missed it) there was a new June 20th build that had been posted, and it fixes all the issues here. Thanks and cheers!

**Comment by nullobject** [comment] 2020-06-30 23:09
@Left-Empty Oh great, I'm glad to hear it :tada: 

I also have been running the core perfectly fine on my new 128MB module.

I didn't make any changes to the SDRAM controller, so I wonder what changed? Maybe routing caused very subtle variations in the timing of the SDRAM signals. I'll have to double-check my SDRAM timing constraints and see if I have missed anything.

I'm going to mark this issue as closed for now.

**Comment by mdd45** [comment] 2020-07-01 13:49
still having the same issues with 20/6/20 build.....

**Comment by nullobject** [comment] 2020-07-01 22:03
> still having the same issues with 20/6/20 build.....

@mdd45 That’s a shame. I have reopened this issue.

A couple questions:

* Which SDRAM module are you using (size, version, etc.)?
* Is it only Rygar that is having issues? What about Silkworm or Gemini Wing?

**Comment by mdd45** [comment] 2020-07-01 22:41
I have the 128mb horizontal sdram from antoniovillena. I will retest Gemini and silkworm and let you know asap...rygar for sure is broken for me...

**Comment by Left-Empty** [comment] 2020-07-01 23:09
I tried to reproduce mdd45's steps here, going to check for a later corruption if more gaming was done prior to launching them, but they seem totally fixed and stable here now.

**Comment by mdd45** [comment] 2020-07-02 13:31
re-tested the core and i have problems with all 3 games. Another thing is that even though i configure my gamepad like all the cores in mister, with this core every time i have to reconfigure (i use save settings). Below some pictures with gfx errors. The rygar one is from a game that started ok and  upon entering round 2 i got this. Gemini stuck on demo. On silkwork heli is cut in two and inverted while playing fter a few seconds. I dont have any other problems with other cores and games with my mister setup and my 128mb sdram board is like this: https://github.com/MiSTer-devel/Hardware_alternative

pictures: https://imgur.com/a/Dnqbixp

**Comment by nullobject** [comment] 2020-07-03 01:50
@mdd45 Thanks for the screenshots.

It definitely looks like a SDRAM issue to me. I am currently investigating it :eyes: 

Would you mind testing out a new build when I have something for you?

**Comment by mdd45** [comment] 2020-07-03 06:40
Of course

**Comment by nullobject** [comment] 2020-07-03 07:01
@mdd45 Could you please try this RBF?

You shouldn't have to delete the real tecmo core, I think this one will take priority if you have both in your cores directory.

[tecmo-20200703.zip](https://github.com/MiSTer-devel/Arcade-Tecmo_MiSTer/files/4868210/tecmo-20200703.zip)

**Comment by mdd45** [comment] 2020-07-03 08:44
This looks perfect, it fixed all Tecmo games gfx problems and also now my gamepad configurations are being saved as it should.
Already at round 4 of rygarwith no errors:  https://imgur.com/a/qglCbKA 

It also fixed this issue for me: https://github.com/MiSTer-devel/Arcade-Tecmo_MiSTer/issues/5

so it was an sdram issue?

Thank you!!!

**Comment by nullobject** [comment] 2020-07-03 08:52
@mdd45 Awesome, that's exactly what I need to hear on a Friday night :smile: 

Yes, I adjusted the SDRAM timing. It may have been too strict...everyone's SDRAM chips will perform slightly differently.

If you are interested, I wrote a blog post a while ago about how an SDRAM controller works: https://www.joshbassett.info/sdram-controller/

I'll take a look at what's up with the button configs next. So you edit your config, save, and it goes back to default?

Enjoy!

**Comment by mdd45** [comment] 2020-07-03 08:56
yes i define rygar buttons save and on core rebbotr is default....i will look my config folder again.... on Silkworm and gemini my mappings are ok..... strange.

**Comment by nullobject** [comment] 2020-07-03 08:58
@mdd45 Actually, from memory I may have seen this before.

What happens if you delete the rygar files out of the `/media/fat/config` directory?

**Comment by nullobject** [comment] 2020-07-03 09:00
For now I'm going to close this GFX issue. If you can't get the buttons figured out, then open another issue and we'll work through it :+1:

**Closed by nullobject** 2020-07-03 09:00 UTC

**Comment by mdd45** [comment] 2020-07-03 09:01
nevermind, mappings are stored also for rygar, i had 3 rygar map files in input and maybe and maybe there was a problem. 

i have though to press jump or fire before entering credit for my gamepad to actually being recognized..... so everything looks ok!  

thanks again looking forward you cave core ;-)

**Comment by mdd45** [comment] 2020-07-03 09:04
you should close issue #5 too. it looks ok for me with this build.

**Comment by mdd45** [comment] 2020-07-03 09:06
and issue #1 looks fine for me too on gemini wing.

**Comment by nullobject** [comment] 2020-07-03 09:22
> thanks again looking forward you cave core ;-)

@mdd45 Thanks, it's coming along :smiley:

**Comment by wwark** [comment] 2020-07-03 10:21
I confirmed also "It also fixed this issue for me: #5"
I closed the other issue.

**Comment by nullobject** [comment] 2020-07-03 10:22
@wwark Awesome, thanks for checking it.
